In [1]:
import pandas as pd

In [2]:
caminho_pasta = fr"C:\Users\luizh\OneDrive\Aulas Impacta\Cursos Livres\Aulas Udemy\pandas\dados"
arquivo = fr"\receitas.json"

In [4]:
df = pd.read_json(fr"{caminho_pasta}{arquivo}", encoding="utf-8")
df

                                            receitas
0  {'titulo': 'Bolo de Chocolate', 'tempo_preparo...
1  {'titulo': 'Salada Caesar', 'tempo_preparo': '...
2  {'titulo': 'Pasta ao Pesto', 'tempo_preparo': ...

In [5]:
df_receitas = pd.json_normalize(
    df["receitas"],
    "ingredientes",
    ['titulo', 'tempo_preparo', 'porcoes']
)
df_receitas

       ingrediente  quantidade             titulo tempo_preparo porcoes
0   Faria de Trigo   2 xícaras  Bolo de Chocolate    45 minutos       8
0           Açucar    1 xícara  Bolo de Chocolate    45 minutos       8
0             Ovos   3 xícaras  Bolo de Chocolate    45 minutos       8
0            Leite    1 xícara  Bolo de Chocolate    45 minutos       8
0         Manteira    1 xícara  Bolo de Chocolate    45 minutos       8
1    Alface Romana    1 cabeça      Salada Caesar    20 minutos       4
1         Croutons    1 xícara      Salada Caesar    20 minutos       4
1  Queijo Parmesão    1 xícara      Salada Caesar    20 minutos       4
1     Molho Caesar  1/4 xícara      Salada Caesar    20 minutos       4
2    Alface Romana    1 cabeça     Pasta ao Pesto    20 minutos       4
2         Croutons    1 xícara     Pasta ao Pesto    20 minutos       4
2  Queijo Parmesão    1 xícara     Pasta ao Pesto    20 minutos       4
2     Molho Caesar  1/4 xícara     Pasta ao Pesto    20 minutos       4