In [1]:
import pandas as pd

In [2]:
caminho_pasta = fr"C:\Users\luizh\OneDrive\Aulas Impacta\Cursos Livres\Aulas Udemy\pandas\dados"
arquivo = fr"\campeonato_futebol.xlsx"

In [4]:
df = pd.read_excel(fr"{caminho_pasta}{arquivo}")
df

,Times,Partidas_Jogadas,Vitorias,Empates,Derrotas,Gols_Pro,Gols_Contra,Saldo_Gols,Pontos
0,Flamengo,10,7,2,1,22,10,12,23
1,São Paulo,10,6,1,3,16,15,1,19
2,Palmeiras,10,5,3,2,18,12,6,18
3,Santos,10,4,3,3,14,16,-2,15
4,Corinthians,10,3,2,5,10,20,-10,11

In [5]:
df.dtypes

Times                 str
Partidas_Jogadas    int64
Vitorias            int64
Empates             int64
Derrotas            int64
Gols_Pro            int64
Gols_Contra         int64
Saldo_Gols          int64
Pontos              int64
dtype: object

In [6]:
df.describe()

,Partidas_Jogadas,Vitorias,Empates,Derrotas,Gols_Pro,Gols_Contra,Saldo_Gols,Pontos
count,5.0,5.000000,5.00000,5.00000,5.000000,5.000000,5.000000,5.000000
mean,10.0,5.000000,2.20000,2.80000,16.000000,14.600000,1.400000,17.200000
std,0.0,1.581139,0.83666,1.48324,4.472136,3.847077,8.294577,4.494441
min,10.0,3.000000,1.00000,1.00000,10.000000,10.000000,-10.000000,11.000000
25%,10.0,4.000000,2.00000,2.00000,14.000000,12.000000,-2.000000,15.000000
50%,10.0,5.000000,2.00000,3.00000,16.000000,15.000000,1.000000,18.000000
75%,10.0,6.000000,3.00000,3.00000,18.000000,16.000000,6.000000,19.000000
max,10.0,7.000000,3.00000,5.00000,22.000000,20.000000,12.000000,23.000000

In [8]:
df.head(2)

,Times,Partidas_Jogadas,Vitorias,Empates,Derrotas,Gols_Pro,Gols_Contra,Saldo_Gols,Pontos
0,Flamengo,10,7,2,1,22,10,12,23
1,São Paulo,10,6,1,3,16,15,1,19

In [9]:
df.tail(2)

,Times,Partidas_Jogadas,Vitorias,Empates,Derrotas,Gols_Pro,Gols_Contra,Saldo_Gols,Pontos
3,Santos,10,4,3,3,14,16,-2,15
4,Corinthians,10,3,2,5,10,20,-10,11

In [14]:
# Analise de Desempenho por Time
desempenho_info = df[['Times', 'Pontos', 'Vitorias', 'Saldo_Gols', 'Gols_Pro', 'Gols_Contra']].set_index('Times')
desempenho_info

             Pontos  Vitorias  Saldo_Gols  Gols_Pro  Gols_Contra
Times
Flamengo         23         7          12        22           10
São Paulo        19         6           1        16           15
Palmeiras        18         5           6        18           12
Santos           15         4          -2        14           16
Corinthians      11         3         -10        10           20

In [16]:
# Time com mais vitoria e menos vitoria
time_mais_vitoria = df[df['Vitorias'] == df['Vitorias'].max()]
time_mais_vitoria

,Times,Partidas_Jogadas,Vitorias,Empates,Derrotas,Gols_Pro,Gols_Contra,Saldo_Gols,Pontos
0,Flamengo,10,7,2,1,22,10,12,23

In [17]:
# Time com mais vitoria e menos vitoria
time_mais_vitoria = df[df['Vitorias'] == df['Vitorias'].min()]
time_mais_vitoria

,Times,Partidas_Jogadas,Vitorias,Empates,Derrotas,Gols_Pro,Gols_Contra,Saldo_Gols,Pontos
4,Corinthians,10,3,2,5,10,20,-10,11

In [18]:
# Distribuição de Gols Pró
df['Gols_Pro'].value_counts()

Gols_Pro
22    1
16    1
18    1
14    1
10    1
Name: count, dtype: int64

In [20]:
# Relação entre gols pró e pontos
correlacao = df['Gols_Pro'].corr(df['Pontos'])
correlacao

np.float64(0.9701612604547394)

In [21]:
# Relação entre gols contra e pontos
correlacao = df['Gols_Contra'].corr(df['Pontos'])
correlacao

np.float64(-0.934041094880381)